/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        // mono: ["CaskaydiaCove Nerd Font Mono"],
        mono: ["CaskaydiaCoveNFM"],
        tnrpro: ["TimesNewRomanProBold"],
        tnr: ["Times New Roman"],
        firaCode: ["Fira Code"],
      },
      colors: {
        "nosferatu-darker": "#242631",
      },
    },
  },
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
    lightTheme: "dracula",
    darkTheme: "dracula",
  },
  plugins: [require("tailwind-dracula")(), require("daisyui")],
};
